openapi: 3.0.3
info:
  title: Vaadin project
  version: 0.1.9
servers:
  - url: 'https://localhost:8080/api'
    description: Сервер для тестирования
paths:
  /payment:
    get:
      tags:
        - payment-controller
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentOutput'

  /payment/{uuid},{date},{int}:
    get:
      responses:
        '200':
          description: OK
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
          required: true
          description: UUID
        - in: path
          name: date
          schema:
            type: string
            format: date
            pattern: '^\d{4}-\d{2}-\d{2}$'
          required: true
          description: DATE
        - in: path
          name: int
          schema:
            type: integer
            format: integer
          required: true
          description: INTEGER

components:
  schemas:
    PaymentOutput:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
